### ISSUE TITLE
template_alignment

### ISSUE THREAD

**Issue by MacyL** [lingpy/lingrex#20]
when a vowel is missing in the morpheme, the template_alignment reports a incorrect result:  
"f ŋ ³¹³" should be "i c t" , but the alignment result is "i t".

**Comment by LinguList** [comment]
the ŋ is interpreted as a *vocalic consonant* here, as in German.

**Comment by LinguList** [comment]
Can you give more details to the error, please?

**Comment by MacyL** [comment]
Here are the examples  (Chenhmongmien): 
| Segments | Template |
| -----------|----------|
|tɬ e ⁴⁴ + f ŋ ³¹³ + t ŋ ³¹³ | i n t + **i t** + **i t** |
|f ŋ ¹³         |  **i t**  |
| m a ⁵³ + h ŋ ³¹³  | i n t +  **i t**  |
| l au ³⁵ + k ŋ ²³¹ |  i n t + **i t**  |
| tʰ ŋ ⁴⁴ + n u ¹³  | **i t** + i n t |

**Comment by LinguList** [comment]
Okay, so the template is wrong! The template should be "i n t". So we need to update the procedure for conversion.

**Comment by LinguList** [comment]
So, @MacyL, to search for this bug, you need to look into SinoPy, where there is a function that converts a string to a template:
```
In [2]: from sinopy.segments import get_structure                                                                                                                                                                                             

In [3]: get_structure('kn⁵')                                                                                                                                                                                                                  
Out[3]: <generator object get_structure at 0x7f7651369e40>

In [4]: list(get_structure('k n ⁵'))                                                                                                                                                                                                          
Out[4]: [['i', 't']]
```

**Comment by LinguList** [comment]
But, @MacyL, note that we have a check for these cases in our code in `3_alignment.py`:

```
print('[i] added segments')
D = {0: [c for c in alms.columns]}
for idx, tokens, structure in alms.iter_rows('tokens', 'structure'):
    if len(tokens.n) != len(structure.n):
        print('[!!!]', tokens, structure)
    elif len(tokens) != len(structure):
        print('[!]', tokens, structure)
    else:
        D[idx] = alms[idx]
```
As you can see, we exclude those cases, where the stucture string is not of the same length as the tokens string.

**Comment by LinguList** [comment]
See the bug in SinoPy [here](https://github.com/lingpy/sinopy/issues/3).

**Comment by LinguList** [comment]
So it is not a problem of the template alignment, but of the `structure` creation in the data. I suppose that you try to list all cases and modify the string, so `f ŋ ³¹³` should not be segmented in this way in Chen's data, but rather as `f */ə ŋ ³¹³`: in this way, we have a vowel, but we indicate that this vowel is a place holder, it is not the same as a normal `ə`. I guess, this procedure would be best for this purpose.
