### ISSUE TITLE
`find_colexified_alignments` fails in some cases

### ISSUE THREAD

**Issue by LinguList** [lingpy/lingrex#21]
The reason is that the algorithm won't recognize two alignments to be the same when one has a gap more. These cases need to be handled by reducing all gaps in all alignments and THEN comparing their compatiblity.

**Comment by LinguList** [comment]
@MacyL, please check with this code. I did not test it, but I think this should do the trick. We need to run Chen's workflow on this to see if this works.

**Comment by LinguList** [comment]
I can confirm it works now with the latest modification, also to the script for hte paper

**Comment by MacyL** [comment]
ok. Lingrex version stays at 0.1.2, right? I guess I just need to git pull this repository?

**Comment by LinguList** [comment]
veresion will be changed later

**Comment by MacyL** [comment]
Cool! 
I will note it down, because we need to update the lingrex version on code ocean capsule, too.
