### ISSUE TITLE
write_frequency() inflates Frequency: How to use correctly?

### ISSUE THREAD

**Issue by Tarotis** [lingpy/lingrex#42]
I am trying to compute the correspondence for the oliveiraprotopanoan dataset. However, while using `CoPaR.write_patterns()`, the frequency column counts many cases where the actual sound is not attested. Can this be deactivated?

```
cop = CoPaR("data/opp_alg.tsv", segments="tokens", transcription="tokens", ref="cogid")
cop.get_sites()
cop.cluster_sites()
cop.sites_to_pattern()
cop.add_patterns()
cop.write_patterns("data/opp_patterns.tsv", proto="Proto-Panoan")
```

Output:

```
ID | STRUCTURE | FREQUENCY | Proto-Panoan | Amawaka | Chakobo | Chaninawa | Kakataibo | Kapanawa | Katukina | Kaxarari | Kaxinawa | Korubo | Marinawa | Marubo | Matis | Mayoruna | Poyanawa | Shanenawa | Sharanawa | ShipiboKonibo | Yaminawa | Yawanawa | COGNATESETS | CONCEPTS
87-3 | V | 3 | i | i | i | i | i | i | i | a | i | e | i | ĭ | e | e | i | i | i | i | i | i | 120:3, 142:3, 220:4 | canoe / cold / cutia (species of rodent)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

This posits an /e/ for Mayoruna, but it has no item in cognate set 120.  In other cases, the gap is correctly added, but here not. Can this somehow be made stricter?

**Comment by Tarotis** [comment]
@LinguList I accidentally created the issue empty. This is the updated version.

**Comment by LinguList** [comment]
Hm. You have 3 cognate sets here, right? And are you sure that the /e/ for Mayoruna does not occur in at least one of those? I mean, these values are *imputed* in the end, the statement is: 120:3 is like 142:3 and 220:4, and if Mayoruna was present here, we'd expect /e/.

**Comment by Tarotis** [comment]
Yes, it does occur in two of them. But there are also other cases where *i > e, or *i > i, and the imputation seems to pose a problem if we want to know the exact counts of the occurrences. Is it possible to deactivate the imputation and posit a `ø` instead, like in other cases where this is done automatically?

**Comment by LinguList** [comment]
No.

**Comment by LinguList** [comment]
I understand what you want to say here. But it needs different measures here, and there has some experimentation been done in this regard. Simply counting is not working.

**Comment by LinguList** [comment]
The major point is to evaluate how well a pattern is "filled".

**Comment by LinguList** [comment]
And this is not really trivial.

**Comment by LinguList** [comment]
So the way to proceed is to take these patterns as "inspiration point" and then define them for your proto-forms in a hard-coded way, potentially manually.

**Comment by LinguList** [comment]
So we must discuss strategies here.

**Comment by LinguList** [comment]
It would help me if you could specify WHY you need to have actual reflex numbers, or how you would solve the problem that an alignment site is never fully filled? What I could imagine is some kind of a bar chart for each pattern that shows concrete counts on how many times a reflex is reported inside a pattern for a given language. This might be useful.

**Comment by LinguList** [comment]
Just thought about this again: Internally, as we have the reflexes, etc., lingrex represents all sites, so it is easy to count their coverage, and we have experimented with some ways to score them. One way would be to take the square root from the averaged frequencies of all languages for a pattern which are each squared (I think I have even implemented it in lingrex):

```python

def pattern_coverage(frequencies):
    return (sum([x ** 2 for x in frequencies]) / len(frequencies)) ** 0.5
```

This yields:

```
>>> a = [2, 3, 4, 1, 2]
>>> pattern_coverage(a)
2.6076809620810595
```

**Comment by LinguList** [comment]
When assessing regularity, it may indeed be better to resolve to pattern coverage.

**Comment by Tarotis** [comment]
> 
<img width="927" alt="Screenshot 2023-07-14 at 08 21 47" src="https://github.com/lingpy/lingrex/assets/73231722/b6876b10-01a7-4cad-9a57-d0f00d5979c8">

The bar chart for reflexes is exactly what I had planned. If you remember my snippet that I showed yesterday, my idea was to implement some kind of quality check: How many times do the reflexes _actually_ occur? Are there conflicting reflexes for a proto-phoneme?

Of course, this is not intended to be used for actual reconstructions as is. But I think it would make for a nice visualization for certain questions, especially for getting an overview of the actual reflexes. Of course, one can also use the visualization of the patterns in Edictor (and I do so frequently), but I feel like this is a neat way of visualizing the reflexes _in a specific language_. And I think this works better with the raw count, than with imputed reflexes.

**Comment by LinguList** [comment]
If you do a bit of loading copar one time in an  interactive session, you can check out the attributes. In fact: we use tuples to represent cogid and alignment site, and the clusters link to sites. So the counts are easy to compute from within copar.

**Comment by LinguList** [comment]
In fact, you have to run all three steps:

```python
cop.get_sites() # creats cop.sites
cop.cluster_sites() # creates cop.clusters
cop.sites_to_pattern() # creats cop.patterns
```
and check the attributes mentioned above.

- `cop.sites` is a tuple of `cogid, pos` (pos = alignment site) that links to the sound class (the item you get for the structure, usually c or v) and to the actual pattern for that site (remember this!)
- `cop.clusters` is the other way round: it is a condensed (!) imputed pattern that then lists the corresponding sites (which may not have imputed values!)
- `cop.patterns` is again organized by cogid, pos, linking this time however to ALL concretely inferred patterns (i.e. clusters) to which a given alignment site can be assigned, so this is giving you info on fuzzy cognates!

**Comment by LinguList** [comment]
To score a pattern, just do:

```python
def pattern_coverage(frequencies):
    return (sum([x ** 2 for x in frequencies]) / len(frequencies)) ** 0.5

scores = {}
for (structure, pattern), sites in cop.clusters.items():
    score = [0 for i in pattern]
    for cogid, pos in sites:
        site = cop.sites[cogid, pos][1] # remember, site is based on c / v etc., not needed now, since you already have the structure
        for i, sound in enumerate(site):
            if sound != "Ø":
                score[i] += 1
        scores[structure, pattern] = pattern_coverage(score)

print(len([p for p in scores.values() if p > 2]))

**Comment by LinguList** [comment]
For your info: of 501 patterns in your data, about 134 have a pattern coverage > 1.5.

**Comment by LinguList** [comment]
Seems like a disappointing value, but this is about the number of patterns you should take seriously.

**Comment by LinguList** [comment]
BUT! Be careful about the pattern coverage measure, since it does not indicate how large a pattern is. Maybe, this should be combined. 

```
a a - -
- - a a
a a - - 
- - a a
```

this would have `[2 2 2 2] = 2`, which is bad for hte measure. So we need to modify the measure.

**Comment by LinguList** [comment]
So the formular is NOT good for this case!
